### ISSUE TITLE
Low resolution previews on Telegram for macOS

### ISSUE THREAD

**Issue by kevinnio** [halkliff/EmaProject#8]
Hi! Amazing bot! Nevertheless, I think I found a problem with Ema.

If Ema answers an inline request with an image in Telegram for macOS, the image preview is always
low resolution. If you then click the image, the expanded image still looks lowres.

Examples:

![image](https://user-images.githubusercontent.com/4645117/27620888-6bddbf84-5b92-11e7-816c-9842bbdf6e1a.png)

![image](https://user-images.githubusercontent.com/4645117/27620906-830eea8e-5b92-11e7-8a54-6f9f6abdc97e.png)

![image](https://user-images.githubusercontent.com/4645117/27620912-9044516c-5b92-11e7-91ce-7757c56f8141.png)

![image](https://user-images.githubusercontent.com/4645117/27620966-00f4b190-5b93-11e7-842b-705854340cc6.png)

I looked into the code, but since I've got no experience with Telegram bots I'm afraid I can't solve this on my own.

Thanks!

**Comment by halkliff** [comment]
Hi, and thanks for reporting this issue.

As far as I am concerned, on all Telegram platforms, as such the iOS, Android, Telegram for Desktop and Web Telegram, these images loads as full resolution (compacted, as this is default for Telegram).

So I believe this issue is mostly happening on your client. Could you confirm for me if in other platforms this issue occurs?

**Comment by kevinnio** [comment]
Hi and thank you for answer. I'm sorry, I completely forgot about this issue! Let me check again in every platform I can access to.
